spring:
  application:
    name: simple-chat
  threads:
    virtual:
      enabled: true
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
          temperature: 0.1
io:
  github:
    llmagentbuilder:
      chatagent:
        name: Simple Chat
        description: A simple chat service
        usageInstruction: Ask me anything.
        planner:
          systemInstructions: You are a master chef.
          reActJson:
            enabled: false
          simple:
            enabled: true